### ISSUE TITLE
Update get all pokemons action.

### ISSUE THREAD

**Issue by raphaelanjos1** [raphaelanjos1/pokedb#6]
Get pokemons should return all data fields from Pokemon type.

**Comment by clucasalcantara** [comment]
All data is been returned here from the current implementation, didn't get where the problem is, help? :3

<img width="1362" alt="Screen Shot 2020-05-31 at 18 37 03" src="https://user-images.githubusercontent.com/6919712/83363190-cfb91f00-a36d-11ea-96eb-093bf4bc3410.png">

**Comment by clucasalcantara** [comment]
Solved in [this commit](https://github.com/raphaelanjos1/pokedb/commit/103cd31d9167e086ecdfd19e2c6c3429612f2dec)
